on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

name: CI Checks

jobs:
  code_checks:
    name: Typescript, ESLint, Prettier, Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TEST_RELAY_URL: ${{ secrets.TEST_RELAY_URL }}
      TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
      GM_PROJECT_SECRET: ${{ secrets.GM_PROJECT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Check npm cache
        uses: actions/cache@v3
        id: cache-npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Check node_modules cache
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          TEST_RELAY_URL: ${{ secrets.TEST_RELAY_URL }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install NPM Dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier

      # - name: ESLint
      #   run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm run test
